# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Calculator.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x43\x61lculator.proto\"#\n\x0b\x43\x61lcRequest\x12\t\n\x01\x61\x18\x01 \x02(\x05\x12\t\n\x01\x62\x18\x02 \x02(\x05\"\x1e\n\x0c\x43\x61lcResponse\x12\x0e\n\x06result\x18\x01 \x02(\x05\x32\x36\n\nCalculator\x12(\n\x07\x45xecute\x12\x0c.CalcRequest\x1a\r.CalcResponse\"\x00')
)




_CALCREQUEST = _descriptor.Descriptor(
  name='CalcRequest',
  full_name='CalcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='CalcRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='CalcRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=55,
)


_CALCRESPONSE = _descriptor.Descriptor(
  name='CalcResponse',
  full_name='CalcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CalcResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['CalcRequest'] = _CALCREQUEST
DESCRIPTOR.message_types_by_name['CalcResponse'] = _CALCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalcRequest = _reflection.GeneratedProtocolMessageType('CalcRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCREQUEST,
  __module__ = 'Calculator_pb2'
  # @@protoc_insertion_point(class_scope:CalcRequest)
  ))
_sym_db.RegisterMessage(CalcRequest)

CalcResponse = _reflection.GeneratedProtocolMessageType('CalcResponse', (_message.Message,), dict(
  DESCRIPTOR = _CALCRESPONSE,
  __module__ = 'Calculator_pb2'
  # @@protoc_insertion_point(class_scope:CalcResponse)
  ))
_sym_db.RegisterMessage(CalcResponse)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=89,
  serialized_end=143,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='Calculator.Execute',
    index=0,
    containing_service=None,
    input_type=_CALCREQUEST,
    output_type=_CALCRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
